
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20150326 (SVN rev 63)
//----------------------------------------------------

package lexer;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int MULTIPLICACION = 14;
  public static final int ELSE = 5;
  public static final int IDENT = 9;
  public static final int IGUAL = 11;
  public static final int WHILE = 7;
  public static final int PUNTCOMA = 20;
  public static final int DIVISION = 15;
  public static final int SUMA = 12;
  public static final int RETURN = 8;
  public static final int POTENCIA = 16;
  public static final int FUNCTION = 3;
  public static final int IF = 4;
  public static final int COMA = 19;
  public static final int EOF = 0;
  public static final int NUMBER = 10;
  public static final int BLOQAB = 21;
  public static final int MAIN = 2;
  public static final int PARENder = 18;
  public static final int error = 1;
  public static final int PARENTizq = 17;
  public static final int FOR = 6;
  public static final int BLOQCR = 22;
  public static final int RESTA = 13;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "MAIN",
  "FUNCTION",
  "IF",
  "ELSE",
  "FOR",
  "WHILE",
  "RETURN",
  "IDENT",
  "NUMBER",
  "IGUAL",
  "SUMA",
  "RESTA",
  "MULTIPLICACION",
  "DIVISION",
  "POTENCIA",
  "PARENTizq",
  "PARENder",
  "COMA",
  "PUNTCOMA",
  "BLOQAB",
  "BLOQCR"
  };
}

