
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20150326 (SVN rev 63)
//----------------------------------------------------

package lexer;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int FLOAT_LIT = 15;
  public static final int CHAR_LIT = 17;
  public static final int WHEN = 52;
  public static final int T_FLOAT = 8;
  public static final int GE = 32;
  public static final int PARENder = 40;
  public static final int RESTA = 21;
  public static final int T_INT = 7;
  public static final int INTDIV = 24;
  public static final int FOR = 53;
  public static final int CORCHder = 42;
  public static final int NOT = 37;
  public static final int AND = 35;
  public static final int ENDL = 6;
  public static final int IGUAL = 19;
  public static final int LT = 29;
  public static final int DECIDE = 46;
  public static final int OR = 36;
  public static final int BLOQAB = 44;
  public static final int INC = 27;
  public static final int SUMA = 20;
  public static final int EXIT = 51;
  public static final int LOOP = 50;
  public static final int MAIN = 2;
  public static final int T_CHAR = 10;
  public static final int LE = 30;
  public static final int OF = 47;
  public static final int EOF = 0;
  public static final int RETURN = 54;
  public static final int error = 1;
  public static final int COMA = 43;
  public static final int BLOQCR = 45;
  public static final int MODULO = 25;
  public static final int NEQ = 34;
  public static final int BREAK = 55;
  public static final int WORLD = 4;
  public static final int IDENT = 13;
  public static final int EQ = 33;
  public static final int T_STRING = 11;
  public static final int POTENCIA = 26;
  public static final int ARROW = 38;
  public static final int T_COAL = 12;
  public static final int ELSE = 48;
  public static final int T_BOOL = 9;
  public static final int CORCHizq = 41;
  public static final int BOOL_LIT = 16;
  public static final int END = 49;
  public static final int LOCAL = 5;
  public static final int DEC = 28;
  public static final int DIVISION = 23;
  public static final int STRING_LIT = 18;
  public static final int INT_LIT = 14;
  public static final int GT = 31;
  public static final int PARENTizq = 39;
  public static final int GIFT = 3;
  public static final int MULTIPLICACION = 22;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "MAIN",
  "GIFT",
  "WORLD",
  "LOCAL",
  "ENDL",
  "T_INT",
  "T_FLOAT",
  "T_BOOL",
  "T_CHAR",
  "T_STRING",
  "T_COAL",
  "IDENT",
  "INT_LIT",
  "FLOAT_LIT",
  "BOOL_LIT",
  "CHAR_LIT",
  "STRING_LIT",
  "IGUAL",
  "SUMA",
  "RESTA",
  "MULTIPLICACION",
  "DIVISION",
  "INTDIV",
  "MODULO",
  "POTENCIA",
  "INC",
  "DEC",
  "LT",
  "LE",
  "GT",
  "GE",
  "EQ",
  "NEQ",
  "AND",
  "OR",
  "NOT",
  "ARROW",
  "PARENTizq",
  "PARENder",
  "CORCHizq",
  "CORCHder",
  "COMA",
  "BLOQAB",
  "BLOQCR",
  "DECIDE",
  "OF",
  "ELSE",
  "END",
  "LOOP",
  "EXIT",
  "WHEN",
  "FOR",
  "RETURN",
  "BREAK"
  };
}
